# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-HEADRegistry
version:      0.01
version_from: HEADRegistry.pm
installdirs:  site
requires:
    mod_perl:                      1.26

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
